Update keyboard customization instructions
system76/ec pull request #184
Opened 2021-04-25 22:05 UTC by larsblumberg

People who are just reading the keyboard customization instructions might not be aware of the readme file in the root directory which lists an additional build step, namely how to install the build dependencies

2021-04-27 14:37 UTC, leviport commented
I'd rather not have information duplicated in multiple places. That's just a recipe for things not getting updated. If you think the dependencies section is too easy to miss, I guess a note along the lines of "Make sure all dependencies are installed (see above)" would be okay. 

If we're going to include the cargo env sourcing command, I'd prefer that only went into README.md.

2021-04-28 09:44 UTC, larsblumberg commented
@leviport I have made the changes as requested by you. Additionally, I've added a paragraph about the sourcing of cargo's env vars to avoid people like me new to rustup/cargo run into build failures.

2021-04-28 13:00 UTC, leviport approved these changes
Looks great, thank you for the contribution!

2021-04-28 13:08 UTC, crawfxrd requested changes
Please squash the commits as fixups.

2021-04-28 16:50 UTC, crawfxrd approved these changes

2021-04-28 16:50 UTC, larsblumberg commented
@crawfxrd Squashed!

2021-04-28 16:55 UTC, jackpot51 approved these changes

2021-05-03 22:25 UTC, merged